---
deployment:
  tasks:
    # Salir ante cualquier error y mostrar info básica
    - set -euo pipefail
    - echo "Branch: $(git rev-parse --abbrev-ref HEAD || echo HEAD)"
    # ✅ Solo ejecutar si la rama es master
    - BRANCH="$(git rev-parse --abbrev-ref HEAD || echo HEAD)"
    - if [ "$BRANCH" != "master" ]; then echo "Skip deploy: $BRANCH != master"; exit 0; fi

    # 📁 Ajusta aquí la carpeta que quieres publicar
    #   Ejemplos Angular:
    #     - dist/miapp/browser  (Angular 17+)
    #     - dist/miapp          (Angular <=16)
    - export SOURCE_DIR="/home/davidort/repositories/davidortega.dev/dist/browser"

    # Destino estándar de cPanel (no hardcodea el usuario)
    - export DEST="/home/davidort/public_html"
    - /bin/mkdir -p "$DEST"

    # 🚀 Sincroniza contenido (borra obsoletos si hay rsync; si no, copia completa)
    - if command -v rsync >/dev/null 2>&1; then
        /bin/rsync -a --delete "$SOURCE_DIR"/ "$DEST"/;
      else
        /bin/rm -rf "$DEST"/*;
        /bin/cp -a "$SOURCE_DIR"/. "$DEST"/;
      fi

    # 🔐 Permisos seguros (opcional)
    - /bin/find "$DEST" -type d -exec chmod 755 {} \;
    - /bin/find "$DEST" -type f -exec chmod 644 {} \;

    - echo "✅ Deploy OK"
