name: Deploy Angular to cPanel via FTPS
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run build -- --configuration=production

      - name: Detect dist
        id: dist
        run: |
          DIST=$(node -e "const p=require('./angular.json');const proj=p.defaultProject||Object.keys(p.projects)[0];process.stdout.write(p.projects[proj].architect.build.options.outputPath)")
          echo "DIST=$DIST" >> $GITHUB_OUTPUT

      - name: Deploy (Via FTP)
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server:     ${{ secrets.FTP_SERVER }}
          user:   ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          local_dir:  ${{ steps.dist.outputs.DIST }}
          remote_dir: /public_html
          max_retries: "7"
          no_symlinks: "false"
          ftp_ssl_allow: "true"
          ftp_use_feat: "true"
          ftp_nop_interval: "9"
          net_max_retries: "0"
          net_persist_retries: "11"
          net_timeout: "13s"
          dns_max_retries: "17"
          dns_fatal_timeout: "never"