name: Deploy Angular to cPanel (FTP Deployment)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (production)
        run: npm run build -- --configuration=production

      # Detecta dist y si existe "browser/" (Angular moderno)
      - name: Detect dist/browser path
        id: paths
        run: |
          DIST=$(node -e "const p=require('./angular.json');const proj=p.defaultProject||Object.keys(p.projects)[0];process.stdout.write(p.projects[proj].architect.build.options.outputPath)")
          if [ -d "$DIST/browser" ]; then
            echo "LOCAL=$DIST/browser" >> $GITHUB_OUTPUT
          else
            echo "LOCAL=$DIST" >> $GITHUB_OUTPUT
          fi
          echo "Using local dir: $(cat $GITHUB_OUTPUT | cut -d= -f2)"

      - name: Deploy via FTP (FTP Deployment action)
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server:   ${{ secrets.FTP_SERVER }}
          user:     ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: ${{ steps.paths.outputs.LOCAL }}
          remote_dir: "/public_html"
          # Si tu hosting requiere FTPS:
          ftp_ssl_allow: "true"
          # Evita borrar en cada deploy (cámbialo a "true" solo para el 1er publish si quieres limpiar):
          delete: "false"
          # Ajustes útiles de lftp para timeouts / pasivo:
          lftp_settings: "set ftp:passive-mode true; set net:timeout 25; set net:max-retries 2; set net:persist-retries 2"
