name: Deploy Angular to cPanel (sebastianpopp/ftp-action)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (production)
        run: npm run build -- --configuration=production

      # ✅ Sin comillas raras ni $() — Node escribe a GITHUB_OUTPUT
      - name: Detect dist path
        id: paths
        shell: bash
        run: |
          node <<'NODE'
          const fs = require('fs');
          const p = require('./angular.json');
          const proj = p.defaultProject || Object.keys(p.projects)[0];
          const dist = p.projects[proj].architect.build.options.outputPath;
          const local = fs.existsSync(`${dist}/browser`) ? `${dist}/browser` : dist;
          fs.appendFileSync(process.env.GITHUB_OUTPUT, `LOCAL=${local}\n`);
          console.log('Using local dir:', local);
          NODE

      - name: Upload via FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host:       ${{ secrets.FTP_SERVER }}
          user:       ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          localDir:   ${{ steps.paths.outputs.LOCAL }}
          remoteDir:  "public_html"
          forceSsl:   true
          # --delete para sincronizar (elim. obsoletos). Quita si no lo deseas.
          options:    "--verbose"
