name: Deploy to cPanel (API)

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cPanel deploy
        uses: pinkasey/cpanel-deploy-action@v1.2.1
        with:
          hostname: https://davidortega.dev
          cpanel_username: davidort
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
          repository_root: ${{ secrets.CPANEL_REPO_ROOT }}
          cPanelApiPort: 2083
          updateRepository: true
          branch: master
