name: Deploy Angular to cPanel (sebastianpopp/ftp-action)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (production)
        run: npm run build -- --configuration=production

      # Detecta la carpeta de salida (browser si existe)
      - name: Detect dist path
        id: paths
        run: |
          DIST=$(node -e "const p=require('./angular.json');const proj=p.defaultProject||Object.keys(p.projects)[0];process.stdout.write(p.projects[proj].architect.build.options.outputPath))"
          if [ -d "$DIST/browser" ]; then
            echo "LOCAL=$DIST/browser" >> $GITHUB_OUTPUT
          else
            echo "LOCAL=$DIST" >> $GITHUB_OUTPUT
          fi
          echo "Usando carpeta: $(cat $GITHUB_OUTPUT | cut -d= -f2)"

      - name: Upload via FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host:       ${{ secrets.FTP_SERVER }}
          user:       ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          localDir:   ${{ steps.paths.outputs.LOCAL }}
          remoteDir:  "public_html"
          forceSsl:   true
          # --delete elimina archivos obsoletos para espejar public_html con tu dist
          # (si no quieres borrar nada, quita --delete)
          options:    "--verbose"
