name: Build and Deploy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for production
      run: npm run build:prod
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

    - name: Deploy to cPanel
      id: deploy
      uses: pinkasey/cpanel-repository-action@v1.2.1
      with:
        hostname: 'https://davidortega.dev'
        cpanel_token: '${{ secrets.CPANEL_TOKEN }}'
        cpanel_username: 'davidort'
        repository_root: '/home/davidort/repositories/davidortega.dev'
        branch: main

    - name: echo deploy-duration
      run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"