name: Build and Deploy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for production
      run: npm run build:prod
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        
    - name: Deploy to GitHub Pages
      uses: angular-cli-ghpages@v2.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dist_folder: dist/browser
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'